sudo: require
language: cpp
compiler: gcc

addons: 
  apt: 
    packages: libboost1.48-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:marutter/rrutter 
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-4.8 
  - sudo apt-get install -qq g++-5
  - apt-cache search libboost #Perhaps there are newer versions?
  - sudo apt-get install -qq r-base r-base-dev 
  - sudo apt-get install -qq lyx
  - sudo apt-get install -qq texlive
  - sudo pip install codecov

before_script: 
 - ./download_other_githubs.sh

script: 
 - ./build_cpp_test_debug.sh
 - ./get_code_cov.sh
 - codecov
 - ./build_cpp_test_release.sh
 - ./clean.sh 
 # The next packages are built with -lgcov
 - ./build_cpp_exe_release.sh
 - ./build_cpp_exe_debug.sh
 - ./clean.sh
 - sudo Rscript install_r_packages.R
 # R wants all hidden files gone...
 - rm .gitignore
 - rm src/.gitignore
 - rm .travis.yml
 - rm -rf .git
 - rm -rf ..Rcheck
 # Now R is ready to go
 - R CMD check .

after_failure:
 # Couldn't find any package by regex 'libboost*', where * is the package I chose
 - apt-cache search libboost
 # fatal error: Rcpp.h: No such file or directory
 - find / -name 'Rcpp.h'
 # R logs
 - cat /home/travis/build/richelbilderbeek/distancer/..Rcheck/00install.out

