sudo: true
language: cpp
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
#  - sudo add-apt-repository -y ppa:lyx-devel/release; 
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; 
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5 
#  - sudo apt-get install -qq lyx texlive pgf

script: 
 - ./build_cpp.sh
# - ./create_pdf.sh
