---
title: "Demo"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(distancer)
library(ggplot2)
library(reshape2)
library(scales)
```


# Four species

Here is a run that temporarily has four species:

```{r}
df <- do_simulation_r(
  max_genetic_distance = 1,
  mutation_rate = 0.1,
  n_generations = 2650,
  n_pin = 4,
  n_sil = 4,
  population_size = 10,
  results_filename = "results.csv",
  rng_seed = 30,
  sampling_interval = 1
)
m <- melt(data = df, id = c("t"))
colnames(m) <- c("t", "id", "f")

# species abundances through time
satt <- ggplot(data = m, aes(x = t, y = f, group = id, colour = id)) + 
  geom_line() + 
  scale_y_discrete() + 
  theme(legend.position = "bottom") + 
  labs(title = "species abundances through time")

satt

```

Zooming in on were the action is:

```{r}
n <- subset(x = m, t > 2500 & t < 2650)

# species abundances through time
satt <- ggplot(data = n, aes(x = t, y = f, group = id, colour = id)) + 
  geom_line() + 
  scale_y_discrete() + 
  theme(legend.position = "bottom") + 
  labs(title = "species abundances through time")

satt
```

# Species being replaced

Here is an example that a species get replaced, zoomed in on 
where the action is:

```{r}
df <- do_simulation_r(
  max_genetic_distance = 1,
  mutation_rate = 0.1,
  n_generations = 1200,
  n_pin = 4,
  n_sil = 4,
  population_size = 20,
  results_filename = "results.csv",
  rng_seed = 40,
  sampling_interval = 1
)
m <- melt(data = df, id = c("t"))
colnames(m) <- c("t", "id", "f")

# species abundances through time
satt <- ggplot(data = m, aes(x = t, y = f, group = id, colour = id)) + 
  geom_line() + 
  scale_y_discrete() + 
  theme(legend.position = "bottom") + 
  labs(title = "species abundances through time")

satt
```

Zooming in on were the action is:

```{r}
n <- subset(x = m, t > 1010 & t < 1015)

# species abundances through time
satt <- ggplot(data = n, aes(x = t, y = f, group = id, colour = id)) + 
  geom_line() + 
  scale_y_discrete() + 
  theme(legend.position = "bottom") + 
  labs(title = "species abundances through time")

satt
```


