# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The function that does a simulation.
#' @param max_genetic_distance the maximum number of different loci that two individuals can still produce viable offspring with
#' @param mutation_rate DNA mutation rate
#' @param n_generations number of generations
#' @param n_loci number of loci
#' @param population_size population size
#' @param rng_seed random number generator seed
#' @param sampling_interval after how many generations is the population sampled for species abundances
#' @return Nothing
#' @export
do_simulation_cpp <- function(max_genetic_distance, mutation_rate, n_generations, n_loci, population_size, rng_seed, sampling_interval) {
    invisible(.Call('distancer_do_simulation_cpp', PACKAGE = 'distancer', max_genetic_distance, mutation_rate, n_generations, n_loci, population_size, rng_seed, sampling_interval))
}

