# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The function that does a simulation.
#' @param max_genetic_distance the maximum number of different loci that two individuals can still produce viable offspring with
#' @param mutation_rate DNA mutation rate
#' @param n_generations number of generations
#' @param n_pin number of Phylogeny Inferring Nucleotides
#' @param n_sil number of Species Identity Loci
#' @param population_size population size
#' @param results_filename the name of the file the results will be written to
#' @param rng_seed random number generator seed
#' @param sampling_interval after how many generations is the population sampled for species abundances
#' @return nothing. A file with name 'results_filename' will be created
#' @export
do_simulation_cpp <- function(max_genetic_distance, mutation_rate, n_generations, n_pin, n_sil, population_size, results_filename, rng_seed, sampling_interval) {
    invisible(.Call('distancer_do_simulation_cpp', PACKAGE = 'distancer', max_genetic_distance, mutation_rate, n_generations, n_pin, n_sil, population_size, results_filename, rng_seed, sampling_interval))
}

